### PR TITLE
Include gitignore for repository

### PR DESCRIPTION
**Pull request by TollyH**
This makes it easier for other people to sync by excluding things like built executables and system specific configuration files from the repository. It also cuts down on making each commit contain unnecessary differences.
I deleted all the files from the repository that are now part of the .gitignore
The repository still contains all the actual code files for the project so everything needed to build the project is still present.

### CODE REVIEW

**Comment by FinJG** [comment]
i agree!

**Comment by FinJG** [comment]
MERGE THE REQUEST NOWWWWWWWWWWW!!!!!!!!!!!!!!!!!!!!!

**Comment by FinJG** [comment]
@DionDune MERGE THE REQUEST NOWWWWWWWWW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
WIN_20230523_09_44_03_Pro

**Comment by DionDune** [comment]
Ooh shit. Wasn't expecting to see this when I opened my email. Cheers

**Pull request merged**
